### ISSUE TITLE
Change scope name to irc?

### ISSUE THREAD

**Issue by tmplt** [Tmplt/libircppclient#7]
A program is most likely not going to use multiple IRC libraries.
And `libircppclient` takes a while to write. `irc` seems more suitable.

**Comment by timofonic** [comment]
What about irclient-lib? :)

**Comment by tmplt** [comment]
<sub><sup>_oh deary me; a comment, on my repo?_</sup></sub>

Doesn't make much sense to me to have the scope being anything other than the library's name or what it does. But if it's the name of it you're talking about, I found it funny to add 'pp' to 'libircclient', the C library.
